### ISSUE TITLE
如果支持抖音等app直接复制出来的链接解析就好了

### ISSUE THREAD

**Issue by zhucaidan** [Baiyuetribe/glink#1]
如果可以支持抖音等app直接复制出来的链接解析就好了

例如：“3.5 JV:/ 出生率的大问题，韩国要消失%经济 %社会 %出生率 %九边  https://v.douyin.com/ejNF8co/ 复制此链接，打開Dou音搜索，直接觀kan視频！”
会提示无效URL

只可以解析：“https://v.douyin.com/ejNF8co/”，但是无法去水印

**Comment by Baiyuetribe** [comment]
感谢反馈，已修复抖音去水印问题，同时新增你说的app分享地址解析

**Comment by alimalls** [comment]
测试了，还是会提示地址无效。
