### ISSUE TITLE
抖音无法解析

### ISSUE THREAD

**Issue by yimouleng** [Baiyuetribe/glink#2]
抖音解析依然有水印

**Comment by Baiyuetribe** [comment]
已修复

**Comment by yimouleng** [comment]
抖音，显示解析失败请检查URL地址，地址没问题。 使用你的demo链接，提示相同

**Comment by Baiyuetribe** [comment]
> 抖音，显示解析失败请检查URL地址，地址没问题。 使用你的demo链接，提示相同

上次为了适配手机端分享链接，正则匹配出问题了，现已解决

**Comment by yimouleng** [comment]
测试已修复成功。辛苦
